services:
  # migration:
  #   build: ./backend
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - NODE_ENV=production
  #   command: npm run migration:run
  # backend:
  #   build: ./backend
  #   container_name: nest-backend
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - mysql

  # seeder:
  #   build: ./backend
  #   depends_on:
  #     migration:
  #       condition: service_completed_successfully
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - NODE_ENV=production
  #   command: npm run seed

  # frontend:
  #   build: ./frontend
  #   container_name: react-frontend
  #   restart: unless-stopped
  #   ports:
  #     - '5173:5173'
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   tty: true
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql_database
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    command: 
      --local-infile=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
